FROM ikodota/nginx-phpfpm-alpine:7.2.1

LABEL maintainer="NGINX-PHPFPM Docker Maintainers <ikodota@gmail.com>"


#COPY nginx.conf /etc/nginx/nginx.conf
#COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf

COPY src/ /var/www/html
